version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vogue-ukraine.postgre
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: VogueUkraine.Identity

  mongo:
    image: mongo:latest
    container_name: vogue-ukraine.mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
